import re
import sys

# 1. Update backend authController.js
auth_ctrl_path = "server/controllers/authController.js"
with open(auth_ctrl_path, "r", encoding="utf-8") as f:
    ctrl_content = f.read()

new_logic = """
// ─── Forgot Password Flow ────────────────────────────────────────────────
const sendResetOtp = async (req, res) => {
  const { identifier } = req.body;
  if (!identifier || !identifier.trim()) {
    return res.status(400).json({ error: 'Email or phone number is required' });
  }

  const cleaned = identifier.trim().toLowerCase();
  const isEmail = /\\S+@\\S+\\.\\S+/.test(cleaned);

  let finalIdentifier = cleaned;
  if (!isEmail) {
    let phone = cleaned;
    if (/^\\d{10}$/.test(phone)) phone = `+91${phone}`;
    if (!/^\\+\\d{10,15}$/.test(phone)) return res.status(400).json({ error: 'Enter a valid phone number' });
    finalIdentifier = phone;
  }

  try {
    const user = await prisma.user.findFirst({
      where: { OR: [{ email: finalIdentifier }, { phone: finalIdentifier }] }
    });

    if (!user) {
      return res.status(404).json({ error: 'No account found with this identifier' });
    }

    const otp = generateOTP();
    storeOTP(finalIdentifier, otp);

    if (isEmail) {
      await sendOTPEmail(finalIdentifier, otp);
    } else {
      await sendSMSOTP(finalIdentifier, otp);
      console.log(`\\n╔══════════════════════════════════════════╗`);
      console.log(`║  RESET PHONE OTP (Generated by Twilio )  ║`);
      console.log(`║  To: ${finalIdentifier.padEnd(34)}║`);
      console.log(`║  Code: ${otp}                              ║`);
      console.log(`╚══════════════════════════════════════════╝\\n`);
    }

    res.json({ message: 'Reset OTP sent', identifier: finalIdentifier });
  } catch (error) {
    console.error('Send reset OTP error:', error);
    res.status(500).json({ error: 'Failed to send reset code' });
  }
};

const resetPassword = async (req, res) => {
  const { identifier, password } = req.body;
  
  if (!identifier || !password) {
    return res.status(400).json({ error: 'Missing required fields' });
  }

  const cleaned = identifier.trim().toLowerCase();

  if (!isVerified(cleaned)) {
    return res.status(400).json({ error: 'Please verify your OTP first' });
  }

  if (password.length < 6) {
    return res.status(400).json({ error: 'Password must be at least 6 characters' });
  }

  const hashedPassword = await hashPassword(password);

  try {
    const user = await prisma.user.findFirst({
      where: { OR: [{ email: cleaned }, { phone: cleaned }] }
    });

    if (!user) return res.status(404).json({ error: 'User not found' });

    await prisma.user.update({
      where: { id: user.id },
      data: { passwordHash: hashedPassword }
    });

    clearOTP(cleaned);

    res.json({ message: 'Password reset successfully' });
  } catch (err) {
    console.error('Reset password error:', err);
    res.status(500).json({ error: 'Failed to reset password' });
  }
};

module.exports = {"""

ctrl_content = ctrl_content.replace('module.exports = {', new_logic)
ctrl_content = ctrl_content.replace('googleSignIn,\n};', 'googleSignIn,\n  sendResetOtp,\n  resetPassword,\n};')

with open(auth_ctrl_path, "w", encoding="utf-8") as f:
    f.write(ctrl_content)


# 2. Update backend authRoutes.js
auth_routes_path = "server/routes/authRoutes.js"
with open(auth_routes_path, "r", encoding="utf-8") as f:
    routes_content = f.read()

routes_content = routes_content.replace(
    '  googleSignIn,\n} = require(',
    '  googleSignIn,\n  sendResetOtp,\n  resetPassword,\n} = require('
)
routes_content = routes_content.replace(
    'module.exports = router;',
    'router.post(\'/send-reset-otp\', sendResetOtp);\nrouter.post(\'/reset-password\', resetPassword);\n\nmodule.exports = router;'
)

with open(auth_routes_path, "w", encoding="utf-8") as f:
    f.write(routes_content)

print("Backend updated.")
