const { PrismaClient } = require('@prisma/client');
const prisma = new PrismaClient();
const { generateToken, hashPassword, comparePassword } = require('../utils/authUtils');
const { generateOTP, storeOTP, verifyOTP: verifyStoredOTP, isVerified, clearOTP } = require('../utils/otpUtils');
const { sendOTPEmail } = require('../utils/emailService');
const { sendSMSOTP } = require('../utils/smsService');

// ─── Step 1: Send OTP to email or phone ────────────────────────────────────
const sendOtp = async (req, res) => {
  const { identifier } = req.body; // email or phone number

  if (!identifier || !identifier.trim()) {
    return res.status(400).json({ error: 'Email or phone number is required' });
  }

  const cleaned = identifier.trim().toLowerCase();
  const isEmail = /\S+@\S+\.\S+/.test(cleaned);

  // For phone: auto-add country code if 10 digits
  let finalIdentifier = cleaned;
  if (!isEmail) {
    let phone = cleaned;
    if (/^\d{10}$/.test(phone)) {
      phone = `+91${phone}`;
    }
    if (!/^\+\d{10,15}$/.test(phone)) {
      return res.status(400).json({ error: 'Enter a valid phone number with country code (e.g., +91XXXXXXXXXX)' });
    }
    finalIdentifier = phone;
  }

  try {
    // Check if user already exists with this identifier
    const existingUser = await prisma.user.findFirst({
      where: {
        OR: [
          { email: finalIdentifier },
          { phone: finalIdentifier },
        ],
      },
    });

    if (existingUser) {
      return res.status(400).json({ error: 'An account with this identifier already exists. Please sign in.' });
    }

    const otp = generateOTP();
    storeOTP(finalIdentifier, otp);

    if (isEmail) {
      await sendOTPEmail(finalIdentifier, otp);
    } else {
      // For phone, attempt to send via Twilio
      await sendSMSOTP(finalIdentifier, otp);
      
      // Also log it locally just in case Twilio is missing credentials
      console.log(`\n╔══════════════════════════════════════════╗`);
      console.log(`║  PHONE OTP (Generated by Twilio logic)   ║`);
      console.log(`║  To: ${finalIdentifier.padEnd(34)}║`);
      console.log(`║  Code: ${otp}                              ║`);
      console.log(`╚══════════════════════════════════════════╝\n`);
    }

    res.json({
      message: 'Verification code sent successfully',
      type: isEmail ? 'email' : 'phone',
      identifier: finalIdentifier,
    });
  } catch (error) {
    console.error('Send OTP error:', error);
    res.status(500).json({ error: 'Failed to send verification code. Please try again.' });
  }
};

// ─── Step 2: Verify OTP ────────────────────────────────────────────────────
const verifyOtp = async (req, res) => {
  const { identifier, otp } = req.body;

  if (!identifier || !otp) {
    return res.status(400).json({ error: 'Identifier and OTP are required' });
  }

  const result = verifyStoredOTP(identifier.trim(), otp.trim());

  if (!result.valid) {
    return res.status(400).json({ error: result.message });
  }

  res.json({ message: 'OTP verified successfully', verified: true });
};

// ─── Step 3: Complete registration (set name + password) ───────────────────
const completeRegistration = async (req, res) => {
  const { identifier, password, name } = req.body;

  if (!identifier) {
    return res.status(400).json({ error: 'Identifier is required' });
  }

  const cleaned = identifier.trim().toLowerCase();

  if (!isVerified(cleaned)) {
    return res.status(400).json({ error: 'Please verify your email/phone first' });
  }

  if (!password || password.length < 6) {
    return res.status(400).json({ error: 'Password must be at least 6 characters' });
  }

  const isEmail = /\S+@\S+\.\S+/.test(cleaned);
  const hashedPassword = await hashPassword(password);

  try {
    const user = await prisma.user.create({
      data: {
        name: name?.trim() || null,
        email: isEmail ? cleaned : `phone_${cleaned.replace(/\+/g, '')}@expenseiq.local`,
        phone: !isEmail ? cleaned : null,
        passwordHash: hashedPassword,
      },
    });

    clearOTP(cleaned);

    res.status(201).json({
      id: user.id,
      name: user.name,
      email: user.email,
      token: generateToken(user.id),
    });
  } catch (error) {
    console.error('Registration error:', error);
    if (error.code === 'P2002') {
      return res.status(400).json({ error: 'An account with this email/phone already exists.' });
    }
    res.status(500).json({ error: 'Failed to create account. Please try again.' });
  }
};

// ─── Login with email/phone + password ─────────────────────────────────────
const loginUser = async (req, res) => {
  const { identifier, password } = req.body;

  if (!identifier || !password) {
    return res.status(400).json({ error: 'Email/phone and password are required' });
  }

  const cleaned = identifier.trim().toLowerCase();

  try {
    const user = await prisma.user.findFirst({
      where: {
        OR: [
          { email: cleaned },
          { phone: cleaned },
        ],
      },
    });

    if (user && user.passwordHash && (await comparePassword(password, user.passwordHash))) {
      res.json({
        id: user.id,
        name: user.name,
        email: user.email,
        token: generateToken(user.id),
      });
    } else {
      res.status(401).json({ error: 'Invalid email/phone or password' });
    }
  } catch (error) {
    console.error('Login error:', error);
    res.status(500).json({ error: 'Server error during login' });
  }
};

// ─── Google sign-in (sync Firebase user with our DB) ───────────────────────
const googleSignIn = async (req, res) => {
  const { email, name, googleId } = req.body;

  if (!email || !googleId) {
    return res.status(400).json({ error: 'Email and Google ID are required' });
  }

  try {
    // Find existing user by googleId or email
    let user = await prisma.user.findFirst({
      where: {
        OR: [
          { googleId },
          { email: email.toLowerCase() },
        ],
      },
    });

    if (user) {
      // Update googleId if not set yet (user might have registered with email first)
      if (!user.googleId) {
        user = await prisma.user.update({
          where: { id: user.id },
          data: { googleId },
        });
      }
    } else {
      // Create new user
      user = await prisma.user.create({
        data: {
          name: name || null,
          email: email.toLowerCase(),
          googleId,
        },
      });
    }

    res.json({
      id: user.id,
      name: user.name,
      email: user.email,
      token: generateToken(user.id),
    });
  } catch (error) {
    console.error('Google sign-in error:', error);
    res.status(500).json({ error: 'Failed to sign in with Google' });
  }
};


// ─── Forgot Password Flow ────────────────────────────────────────────────
const sendResetOtp = async (req, res) => {
  const { identifier } = req.body;
  if (!identifier || !identifier.trim()) {
    return res.status(400).json({ error: 'Email or phone number is required' });
  }

  const cleaned = identifier.trim().toLowerCase();
  const isEmail = /\S+@\S+\.\S+/.test(cleaned);

  let finalIdentifier = cleaned;
  if (!isEmail) {
    let phone = cleaned;
    if (/^\d{10}$/.test(phone)) phone = `+91${phone}`;
    if (!/^\+\d{10,15}$/.test(phone)) return res.status(400).json({ error: 'Enter a valid phone number' });
    finalIdentifier = phone;
  }

  try {
    const user = await prisma.user.findFirst({
      where: { OR: [{ email: finalIdentifier }, { phone: finalIdentifier }] }
    });

    if (!user) {
      return res.status(404).json({ error: 'No account found with this identifier' });
    }

    const otp = generateOTP();
    storeOTP(finalIdentifier, otp);

    if (isEmail) {
      await sendOTPEmail(finalIdentifier, otp);
    } else {
      await sendSMSOTP(finalIdentifier, otp);
      console.log(`\n╔══════════════════════════════════════════╗`);
      console.log(`║  RESET PHONE OTP (Generated by Twilio )  ║`);
      console.log(`║  To: ${finalIdentifier.padEnd(34)}║`);
      console.log(`║  Code: ${otp}                              ║`);
      console.log(`╚══════════════════════════════════════════╝\n`);
    }

    res.json({ message: 'Reset OTP sent', identifier: finalIdentifier });
  } catch (error) {
    console.error('Send reset OTP error:', error);
    res.status(500).json({ error: 'Failed to send reset code' });
  }
};

const resetPassword = async (req, res) => {
  const { identifier, password } = req.body;
  
  if (!identifier || !password) {
    return res.status(400).json({ error: 'Missing required fields' });
  }

  const cleaned = identifier.trim().toLowerCase();

  if (!isVerified(cleaned)) {
    return res.status(400).json({ error: 'Please verify your OTP first' });
  }

  const passwordRegex = /^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[@$!%*?&._#\^+-]).{8,}$/;
  if (!passwordRegex.test(password)) {
    return res.status(400).json({ error: 'Password must be at least 8 chars and include uppercase, lowercase, number, and symbol' });
  }

  const hashedPassword = await hashPassword(password);

  try {
    const user = await prisma.user.findFirst({
      where: { OR: [{ email: cleaned }, { phone: cleaned }] }
    });

    if (!user) return res.status(404).json({ error: 'User not found' });

    await prisma.user.update({
      where: { id: user.id },
      data: { passwordHash: hashedPassword }
    });

    clearOTP(cleaned);

    res.json({ message: 'Password reset successfully' });
  } catch (err) {
    console.error('Reset password error:', err);
    res.status(500).json({ error: 'Failed to reset password' });
  }
};

// ─── Guest Login ─────────────────────────────────────────────────────────
const guestLogin = async (req, res) => {
  try {
    const guestEmail = 'guest@expenseiq.local';
    let user = await prisma.user.findFirst({ where: { email: guestEmail } });
    
    if (!user) {
      user = await prisma.user.create({
        data: {
          name: 'Guest User',
          email: guestEmail,
        }
      });
    }
    
    res.json({
      id: user.id,
      name: user.name,
      email: user.email,
      token: generateToken(user.id),
      isGuest: true
    });
  } catch (error) {
    console.error('Guest login error:', error);
    res.status(500).json({ error: 'Server error during guest login' });
  }
};

module.exports = {
  sendOtp,
  verifyOtp,
  completeRegistration,
  loginUser,
  googleSignIn,
  sendResetOtp,
  resetPassword,
  guestLogin,
};
